INSERT INTO public."COUNTRY"("NAME_ES", "NAME_EN") VALUES
    ('Argentina', 'Argentina'),
    ('Belice', 'Belice'),
    ('Brasil', 'Brasil'),
    ('Canadá', 'Canadá'),
    ('Chile', 'Chile'),
    ('Colombia', 'Colombia'),
    ('Costa Rica', 'Costa Rica'),
    ('Ecuador', 'Ecuador'),
    ('El Salvador', 'El Salvador'),
    ('Estados Unidos', 'El Salvador'),
    ('Guatemala', 'Guatemala'),
    ('Honduras', 'Honduras'),
    ('México', 'México'),
    ('Nicaragua', 'Nicaragua'),
    ('Panamá', 'Panamá'),
    ('Paraguay', 'Paraguay'),
    ('Peru', 'Peru'),
    ('Uruguay', 'Uruguay'),
    ('Venezuela', 'Venezuela'),
		('Bolivia', 'Bolivia');