INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('25','Cantagallo','Cantagallo'),
('25','Cañasgordas','Cañasgordas'),
('25','Caño Colorado','Caño Colorado'),
('25','Caparrapi','Caparrapi'),
('25','Capellania','Capellania'),
('25','Capitanejo','Capitanejo'),
('25','Caqueza','Caqueza'),
('25','Caracoli','Caracoli'),
('25','Caramanta','Caramanta'),
('25','Carcasi','Carcasi'),
('25','Carepa','Carepa'),
('25','Carmen de Apicala','Carmen de Apicala'),
('25','Carmen de Carupa','Carmen de Carupa'),
('25','Carolina','Carolina'),
('25','Cartagena','Cartagena'),
('25','Cartagena del Chaira','Cartagena del Chaira'),
('25','Cartagenita','Cartagenita'),
('25','Cártago','Cártago'),
('25','Caruru','Caruru'),
('25','Casabe Ecopetrol','Casabe Ecopetrol'),
('25','Casabianca','Casabianca'),
('25','Castilla','Castilla'),
('25','Castilla la Nueva','Castilla la Nueva'),
('25','Castro','Castro'),
('25','Caucasia','Caucasia'),
('25','Cerete','Cerete'),
('25','Cerinza','Cerinza'),
('25','Cerrito','Cerrito'),
('25','Cerro Basal','Cerro Basal'),
('25','Cerro de San Antonio','Cerro de San Antonio'),
('25','Cerro La Peña','Cerro La Peña'),
('25','Cerromatoso','Cerromatoso'),
('25','Cestillal','Cestillal'),
('25','Chaguani','Chaguani'),
('25','Chalan','Chalan'),
('25','Chameza','Chameza'),
('25','Chaparral','Chaparral'),
('25','Chapinero','Chapinero'),
('25','Charala','Charala'),
('25','Charta','Charta'),
('25','Chenche Asoleado','Chenche Asoleado'),
('25','Chia','Chia'),
('25','Chicoral','Chicoral'),
('25','Chigorodo','Chigorodo'),
('25','Chima','Chima'),
('25','Chimichagua','Chimichagua'),
('25','Chimila','Chimila'),
('25','Chinacota','Chinacota'),
('25','Chinauta','Chinauta'),
('25','Chinavita','Chinavita'),
('25','Chinchina','Chinchina'),
('25','Chinu','Chinu'),
('25','Chipaque','Chipaque'),
('25','Chiquinquira','Chiquinquira'),
('25','Chiriguana','Chiriguana'),
('25','Chiscas','Chiscas'),
('25','Chita','Chita'),
('25','Chitaga','Chitaga'),
('25','Chitaraque','Chitaraque'),
('25','Chivolo','Chivolo'),
('25','Chivor','Chivor'),
('25','Choachi','Choachi'),
('25','Choconta','Choconta'),
('25','Ciénaga','Ciénaga'),
('25','Ciénaga de Oro','Ciénaga de Oro'),
('25','Ciénega','Ciénega'),
('25','Cimitarra','Cimitarra'),
('25','Circasia','Circasia'),
('25','Cisneros','Cisneros'),
('25','Cite','Cite'),
('25','Clemencia','Clemencia'),
('25','Coconuco','Coconuco'),
('25','Cocorna','Cocorna'),
('25','Codazzi','Codazzi'),
('25','Coello','Coello'),
('25','Cogua','Cogua'),
('25','Colón','Colón'),
('25','Coloso','Coloso'),
('25','Combita','Combita'),
('25','Compartel','Compartel'),
('25','Concepción','Concepción'),
('25','Concordia','Concordia'),
('25','Condoto','Condoto'),
('25','Confines','Confines'),
('25','Conmutador Emp Ant. Energía','Conmutador Emp Ant. Energía'),
('25','Contratación','Contratación'),
('25','Convención','Convención'),
('25','Convenio','Convenio'),
('25','Córdoba','Córdoba'),
('25','Corinto','Corinto'),
('25','Corozal','Corozal'),
('25','Corrales','Corrales'),
('25','Costa Rica','Costa Rica'),
('25','Cota','Cota'),
('25','Cotorra','Cotorra'),
('25','Coveñas','Coveñas'),
('25','Coyaima','Coyaima'),
('25','Cravo Norte','Cravo Norte'),
('25','Cubara','Cubara'),
('25','Cubarral','Cubarral'),
('25','Cucaita','Cucaita'),
('25','Cucunuba','Cucunuba'),
('25','Cucuta','Cucuta'),
('25','Cucutilla','Cucutilla'),
('25','Cumaca','Cumaca'),
('25','Cumaral','Cumaral'),
('25','Cumaribo','Cumaribo'),
('25','Cumbal','Cumbal'),
('25','Cunday','Cunday'),
('25','Cupiagua','Cupiagua'),
('25','Curillo','Curillo'),
('25','Curiti','Curiti'),
('25','Currulao','Currulao'),
('25','Curumani','Curumani'),
('25','Cusiana','Cusiana'),
('25','Dabeiba','Dabeiba'),
('25','Dagua','Dagua'),
('25','Darien','Darien'),
('25','de Sotavento','de Sotavento'),
('25','Dibulla','Dibulla'),
('25','Doima','Doima'),
('25','Dolores','Dolores'),
('25','Don Matías','Don Matías'),
('25','Doradal','Doradal'),
('25','Dos Quebradas','Dos Quebradas'),
('25','Dosquebradas','Dosquebradas'),
('25','Duitama','Duitama'),
('25','Durania','Durania'),
('25','Ebejico','Ebejico'),
('25','El aguila','El aguila'),
('25','El Bagre','El Bagre'),
('25','El Banco','El Banco'),
('25','El Billar','El Billar'),
('25','El Bolo San Isidro','El Bolo San Isidro'),
('25','El Bordo','El Bordo'),
('25','El Cairo','El Cairo'),
('25','El Carmen','El Carmen'),
('25','El Carmen de Atrato','El Carmen de Atrato'),
('25','El Carmen de Bolívar','El Carmen de Bolívar'),
('25','El Castillo','El Castillo'),
('25','El Centro','El Centro'),
('25','El Cerrito','El Cerrito'),
('25','El Charco','El Charco'),
('25','El Cocuy','El Cocuy'),
('25','El Colegio','El Colegio'),
('25','El Copey','El Copey'),
('25','El Crucero','El Crucero'),
('25','El Descanse','El Descanse'),
('25','El Doncello','El Doncello'),
('25','El Dovio','El Dovio'),
('25','El Encanto','El Encanto'),
('25','El Espino','El Espino'),
('25','El Guamo','El Guamo'),
('25','El Jardín','El Jardín'),
('25','El Juncal','El Juncal'),
('25','El Molino','El Molino'),
('25','El Paso','El Paso'),
('25','El Paujil','El Paujil'),
('25','El Peñol','El Peñol'),
('25','El Peñón','El Peñón'),
('25','El Piñón','El Piñón'),
('25','El Placer','El Placer'),
('25','El Playon','El Playon'),
('25','El Retén','El Retén'),
('25','El Retorno','El Retorno'),
('25','El Rosal','El Rosal'),
('25','El Tablazo','El Tablazo'),
('25','El Tambo','El Tambo'),
('25','El Tarra','El Tarra'),
('25','El Triunfo','El Triunfo'),
('25','El Vergel','El Vergel'),
('25','Elias','Elias'),
('25','Enciso','Enciso'),
('25','Entrerrios','Entrerrios'),
('25','Espinal','Espinal'),
('25','Facatativa','Facatativa'),
('25','Falan','Falan'),
('25','Falda, Cosanza','Falda, Cosanza'),
('25','Filadelfia','Filadelfia'),
('25','Filandia','Filandia'),
('25','Firavitoba','Firavitoba'),
('25','Flandes','Flandes'),
('25','Florencia','Florencia'),
('25','Floresta','Floresta'),
('25','Florida','Florida'),
('25','Fomeque','Fomeque'),
('25','Fonseca','Fonseca'),
('25','Fortalecillas','Fortalecillas'),
('25','Fortul','Fortul'),
('25','Fosca','Fosca'),
('25','Fraguita','Fraguita'),
('25','Fredonia','Fredonia'),
('25','Fresno','Fresno'),
('25','Frontino','Frontino'),
('25','Fuente de Oro','Fuente de Oro'),
('25','Fundación','Fundación'),
('25','Funes','Funes'),
('25','Funza','Funza'),
('25','Fuquene','Fuquene'),
('25','Fusagasuga','Fusagasuga'),
('25','Gachala','Gachala'),
('25','Gachancipa','Gachancipa'),
('25','Gacheta','Gacheta'),
('25','Gaitania','Gaitania'),
('25','Galán','Galán'),
('25','Galapa','Galapa'),
('25','Galeras','Galeras'),
('25','Gama','Gama'),
('25','Gamarra','Gamarra'),
('25','Gámbita','Gámbita'),
('25','Gameza','Gameza'),
('25','Garagoa','Garagoa'),
('25','Garzón','Garzón'),
('25','Génova','Génova'),
('25','Gigante','Gigante'),
('25','Ginebra','Ginebra'),
('25','Giraldo','Giraldo'),
('25','Girardot','Girardot'),
('25','Gómez Plata','Gómez Plata'),
('25','Gonzales','Gonzales'),
('25','Gramalote','Gramalote'),
('25','Granada','Granada'),
('25','Guaca','Guaca'),
('25','Guacari','Guacari'),
('25','Guacas','Guacas'),
('25','Guachene','Guachene'),
('25','Guacheta','Guacheta'),
('25','Guachucal','Guachucal'),
('25','Guadalupe','Guadalupe'),
('25','Guaduas','Guaduas'),
('25','Guaitarilla','Guaitarilla'),
('25','Gualanday','Gualanday'),
('25','Gualmatan','Gualmatan'),
('25','Guamal','Guamal'),
('25','Guamalito','Guamalito'),
('25','Guamo','Guamo'),
('25','Guapi','Guapi'),
('25','Guaranda','Guaranda'),
('25','Guarinocito','Guarinocito'),
('25','Guasca','Guasca'),
('25','Guatape','Guatape'),
('25','Guataqui','Guataqui'),
('25','Guatavita','Guatavita'),
('25','Guateque','Guateque'),
('25','Guatica','Guatica'),
('25','Guavata','Guavata'),
('25','Guayabal','Guayabal'),
('25','Guayabal de Siquima','Guayabal de Siquima'),
('25','Guayabetal','Guayabetal'),
('25','Guayata','Guayata'),
('25','Guepsa','Guepsa'),
('25','Güicán','Güicán'),
('25','Gutierrez','Gutierrez'),
('25','Hacari','Hacari'),
('25','Hatillo de Loba','Hatillo de Loba'),
('25','Hato Corozal','Hato Corozal'),
('25','Hatonuevo','Hatonuevo'),
('25','Heliconia','Heliconia'),
('25','Herrán','Herrán'),
('25','Herveo','Herveo'),
('25','Hispania','Hispania'),
('25','Hobo','Hobo'),
('25','Honda','Honda'),
('25','Hoyo Rico','Hoyo Rico'),
('25','Ibague','Ibague'),
('25','Icononzo','Icononzo'),
('25','Ing Mayáguez','Ing Mayáguez'),
('25','Ing Pichichi','Ing Pichichi'),
('25','Inza','Inza'),
('25','Ipiales','Ipiales'),
('25','Iquira','Iquira'),
('25','Irra','Irra'),
('25','Isaza','Isaza'),
('25','Iscuande','Iscuande'),
('25','Isla Mucura','Isla Mucura'),
('25','Istmina','Istmina'),
('25','Ituango','Ituango'),
('25','Iza','Iza'),
('25','Jambalo y Pitayo','Jambalo y Pitayo'),
('25','Jamundi','Jamundi'),
('25','Jardín','Jardín'),
('25','Jenezano','Jenezano'),
('25','Jericó','Jericó'),
('25','Jerusalén','Jerusalén'),
('25','Juan de Acosta','Juan de Acosta'),
('25','Juanchaco-Ladril','Juanchaco-Ladril'),
('25','Junin','Junin'),
('25','Jurado','Jurado'),
('25','La Apartada','La Apartada'),
('25','La Arada','La Arada'),
('25','La Argentina','La Argentina'),
('25','La Bamba','La Bamba'),
('25','La Bocana','La Bocana'),
('25','La Buitrera','La Buitrera'),
('25','La Calera','La Calera'),
('25','La Capilla','La Capilla'),
('25','La Caro','La Caro'),
('25','La Ceiba','La Ceiba'),
('25','La Celia','La Celia'),
('25','La Chamba','La Chamba'),
('25','La China','La China'),
('25','La Chinita','La Chinita'),
('25','La Chorrera','La Chorrera'),
('25','La Cruz','La Cruz'),
('25','La Cruzada','La Cruzada'),
('25','La Cumbre','La Cumbre'),
('25','La Dolores','La Dolores'),
('25','La Donjuana','La Donjuana'),
('25','La Dorada','La Dorada'),
('25','La Esmeralda','La Esmeralda'),
('25','La Esperanza','La Esperanza'),
('25','La Florida','La Florida'),
('25','La Gabarra','La Gabarra'),
('25','La Gloria','La Gloria'),
('25','La Herradura','La Herradura'),
('25','La Herrera','La Herrera'),
('25','La Hormiga','La Hormiga'),
('25','La Horqueta','La Horqueta'),
('25','La Jagua','La Jagua'),
('25','La Jagua de Ibirico','La Jagua de Ibirico'),
('25','La Junta','La Junta'),
('25','La Laguna','La Laguna'),
('25','La Libertad','La Libertad'),
('25','La Loma','La Loma'),
('25','La Macarena','La Macarena'),
('25','La Magdalena','La Magdalena'),
('25','La María','La María'),
('25','La Marina','La Marina'),
('25','La Merced','La Merced'),
('25','La Mesa','La Mesa'),
('25','La Miel','La Miel'),
('25','La Montaña','La Montaña'),
('25','La Montañita','La Montañita'),
('25','La Nubia','La Nubia'),
('25','La Paila','La Paila'),
('25','La Palma','La Palma'),
('25','La Paz','La Paz'),
('25','La Pedrera','La Pedrera'),
('25','La Peña','La Peña'),
('25','La Pintada','La Pintada'),
('25','La Plata','La Plata'),
('25','La Playa','La Playa'),
('25','La Pradera','La Pradera'),
('25','La Primavera','La Primavera'),
('25','La Punta','La Punta'),
('25','La Quiebra','La Quiebra'),
('25','La Sierra','La Sierra'),
('25','La Siria','La Siria'),
('25','La Soledad','La Soledad'),
('25','La Tebaida','La Tebaida'),
('25','La Tola','La Tola'),
('25','La Ulloa','La Ulloa'),
('25','La Unión','La Unión'),
('25','La Uribe','La Uribe'),
('25','La Uvita','La Uvita'),
('25','La Vega','La Vega'),
('25','La Victoria','La Victoria'),
('25','La Virginia','La Virginia'),
('25','Labateca','Labateca'),
('25','Lagos del Dorado','Lagos del Dorado'),
('25','Landazuri','Landazuri'),
('25','Las Lajas','Las Lajas'),
('25','Las Mercedes','Las Mercedes'),
('25','Laureano Gómez','Laureano Gómez'),
('25','Lebrija','Lebrija'),
('25','Lejanías','Lejanías'),
('25','Lenguazaque','Lenguazaque'),
('25','Lérida','Lérida'),
('25','Leticia','Leticia'),
('25','Líbano','Líbano'),
('25','Liborina','Liborina'),
('25','Llanadas','Llanadas'),
('25','Llanos de Cuiba','Llanos de Cuiba'),
('25','Lloro','Lloro'),
('25','López de Micay','López de Micay'),
('25','Lorica','Lorica'),
('25','Los cordobas','Los cordobas'),
('25','Los Córdobas','Los Córdobas'),
('25','Los Palmitos','Los Palmitos'),
('25','Los Santos','Los Santos'),
('25','Lourdes','Lourdes'),
('25','Luruaco','Luruaco'),
('25','Macanal','Macanal'),
('25','Maceo','Maceo'),
('25','Macheta','Macheta'),
('25','Madgalena Medio','Madgalena Medio'),
('25','Madrid','Madrid'),
('25','Magangue','Magangue'),
('25','Magui','Magui'),
('25','Maguncia','Maguncia'),
('25','Mahates','Mahates'),
('25','Maicao','Maicao'),
('25','Maito','Maito'),
('25','Majagual','Majagual'),
('25','Málaga','Málaga'),
('25','Malagana','Malagana'),
('25','Managru','Managru'),
('25','Manati','Manati'),
('25','Manaure','Manaure'),
('25','Mandiguilla','Mandiguilla'),
('25','Mani','Mani'),
('25','Manizales','Manizales'),
('25','Manta','Manta'),
('25','Manzanares','Manzanares'),
('25','Mapiripán','Mapiripán'),
('25','Marandua','Marandua'),
('25','Margarita','Margarita'),
('25','María La Baja','María La Baja'),
('25','Mariquita','Mariquita'),
('25','Marmato','Marmato'),
('25','Marquetalia','Marquetalia'),
('25','Marsella','Marsella'),
('25','Marulanda','Marulanda'),
('25','Matanza','Matanza'),
('25','Medellín','Medellín'),
('25','Medellín Edatel D.I.D.','Medellín Edatel D.I.D.'),
('25','Media Luna','Media Luna'),
('25','Medina','Medina'),
('25','Melgar','Melgar'),
('25','Mercaderes','Mercaderes'),
('25','Mesa de Los Santos','Mesa de Los Santos'),
('25','Mesetas','Mesetas'),
('25','Milán','Milán'),
('25','Minas','Minas'),
('25','Miraflores','Miraflores'),
('25','Miranda','Miranda'),
('25','Mistrato','Mistrato'),
('25','Mitu','Mitu'),
('25','Mocoa','Mocoa'),
('25','Mogotes','Mogotes'),
('25','Molagavita','Molagavita'),
('25','Momil','Momil'),
('25','Mompos','Mompos'),
('25','Mondomo','Mondomo'),
('25','Mongua','Mongua'),
('25','Mongui','Mongui'),
('25','Moniquira','Moniquira'),
('25','Montebello','Montebello'),
('25','Montebonito','Montebonito'),
('25','Montelíbano','Montelíbano'),
('25','Montenegro','Montenegro'),
('25','Monteria','Monteria'),
('25','Montería','Montería'),
('25','Monterrey','Monterrey'),
('25','Montezuma','Montezuma'),
('25','Moñitos','Moñitos'),
('25','Morales','Morales'),
('25','Moreilia','Moreilia'),
('25','Morelia','Morelia'),
('25','Morroa','Morroa'),
('25','Mosquera','Mosquera'),
('25','Murillo','Murillo'),
('25','Murindo','Murindo'),
('25','Mutata','Mutata'),
('25','Mutiscua','Mutiscua'),
('25','Muzo','Muzo'),
('25','Naranjal','Naranjal'),
('25','Nariño','Nariño'),
('25','Nataga','Nataga'),
('25','Natagaima','Natagaima'),
('25','Nechi','Nechi'),
('25','Necocli','Necocli'),
('25','Neira','Neira'),
('25','Neiva','Neiva'),
('25','Nemocon','Nemocon'),
('25','Nilo','Nilo'),
('25','Nimaima','Nimaima'),
('25','Nobsa','Nobsa'),
('25','Nocaima','Nocaima'),
('25','Norcasia','Norcasia'),
('25','Novita','Novita'),
('25','Nueva Colonia','Nueva Colonia'),
('25','Nuevo Colón','Nuevo Colón'),
('25','Nunchia','Nunchia'),
('25','Nuqui','Nuqui'),
('25','Nutibara','Nutibara'),
('25','Obando','Obando'),
('25','Ocaña','Ocaña'),
('25','Oficina Edatel Antioquía (Medellín),','Oficina Edatel Antioquía (Medellín),'),
('25','Oiba','Oiba'),
('25','Olaya Herrera','Olaya Herrera'),
('25','Olival','Olival'),
('25','Onzaga','Onzaga'),
('25','Oporapa','Oporapa'),
('25','Orito','Orito'),
('25','Orocue','Orocue'),
('25','Ortega','Ortega'),
('25','Oru','Oru'),
('25','Otanche','Otanche'),
('25','Ovejas','Ovejas'),
('25','Pacarni','Pacarni'),
('25','Pachavita','Pachavita'),
('25','Pacho','Pacho'),
('25','Pacoa','Pacoa'),
('25','Pacora','Pacora'),
('25','Padilla','Padilla'),
('25','Padua','Padua'),
('25','Paez','Paez'),
('25','Paicol','Paicol'),
('25','Pailitas','Pailitas'),
('25','Paipa','Paipa'),
('25','Paispamba','Paispamba'),
('25','Pajarito','Pajarito'),
('25','Pajonales','Pajonales'),
('25','Palermo','Palermo'),
('25','Palestina','Palestina'),
('25','Palma Real','Palma Real'),
('25','Palmar de Varela','Palmar de Varela'),
('25','Palmarito','Palmarito'),
('25','Palmaseca','Palmaseca'),
('25','Palmira','Palmira'),
('25','Palmito','Palmito'),
('25','Palocabildo','Palocabildo'),
('25','Pamplona','Pamplona'),
('25','Panamá de Arauca','Panamá de Arauca'),
('25','Pandi','Pandi'),
('25','Paratebueno','Paratebueno'),
('25','Pasca','Pasca'),
('25','Pasto','Pasto'),
('25','Patio Bonito','Patio Bonito'),
('25','Pauna','Pauna'),
('25','Payande','Payande'),
('25','Paz de Ariporo','Paz de Ariporo'),
('25','Paz de Río','Paz de Río'),
('25','Pedraza','Pedraza'),
('25','Pelaya','Pelaya'),
('25','Pensilvania','Pensilvania'),
('25','Peque','Peque'),
('25','Pereira','Pereira'),
('25','Pesca','Pesca'),
('25','Pescador','Pescador'),
('25','Pie de Pato','Pie de Pato'),
('25','Piedecuesta','Piedecuesta'),
('25','Piedras','Piedras'),
('25','Piendamo','Piendamo'),
('25','Pijao','Pijao'),
('25','Pinillos','Pinillos'),
('25','Pital','Pital'),
('25','Pitalito','Pitalito'),
('25','Pivijay','Pivijay'),
('25','Pizarro','Pizarro'),
('25','Planadas','Planadas'),
('25','Planeta Rica','Planeta Rica'),
('25','Plato','Plato'),
('25','Playarica','Playarica'),
('25','Polo Nuevo','Polo Nuevo'),
('25','Ponedera','Ponedera'),
('25','Popayan','Popayan'),
('25','Popayán','Popayán'),
('25','Pore','Pore'),
('25','Potosí','Potosí'),
('25','Potrerito','Potrerito'),
('25','Pradera','Pradera'),
('25','Prado','Prado'),
('25','Primavera','Primavera'),
('25','Providencia','Providencia'),
('25','Providencia (Isla),','Providencia (Isla),'),
('25','Pueblo Bello','Pueblo Bello'),
('25','Pueblo Nuevo','Pueblo Nuevo'),
('25','Pueblo Rico','Pueblo Rico'),
('25','Pueblorico','Pueblorico'),
('25','Pueblotapao','Pueblotapao'),
('25','Puente Nacional','Puente Nacional'),
('25','Puente Piedra','Puente Piedra'),
('25','Puente Quetame','Puente Quetame'),
('25','Puente San Miguel','Puente San Miguel'),
('25','Puerres','Puerres'),
('25','Puerto Alegría','Puerto Alegría'),
('25','Puerto Arica','Puerto Arica'),
('25','Puerto Asís','Puerto Asís'),
('25','Puerto Berrio','Puerto Berrio'),
('25','Puerto Bolívar','Puerto Bolívar'),
('25','Puerto Boyaca','Puerto Boyaca'),
('25','Puerto Caicedo','Puerto Caicedo'),
('25','Puerto Carreño','Puerto Carreño'),
('25','Puerto Claver','Puerto Claver'),
('25','Puerto 25','Puerto 25'),
('25','Puerto Concordia','Puerto Concordia'),
('25','Puerto Escondido','Puerto Escondido'),
('25','Puerto Gaitán','Puerto Gaitán'),
('25','Puerto Guzmán','Puerto Guzmán'),
('25','Puerto Inirida','Puerto Inirida'),
('25','Puerto Leguizamo','Puerto Leguizamo'),
('25','Puerto Libertador','Puerto Libertador'),
('25','Puerto Lleras','Puerto Lleras'),
('25','Puerto López','Puerto López'),
('25','Puerto Merizalde','Puerto Merizalde'),
('25','Puerto Nare','Puerto Nare'),
('25','Puerto Nariño','Puerto Nariño'),
('25','Puerto Nuevo','Puerto Nuevo'),
('25','Puerto Ospina','Puerto Ospina'),
('25','Puerto Parra','Puerto Parra'),
('25','Puerto Perales','Puerto Perales'),
('25','Puerto Rico','Puerto Rico'),
('25','Puerto Rondón','Puerto Rondón'),
('25','Puerto Salgar','Puerto Salgar'),
('25','Puerto Santander','Puerto Santander'),
('25','Puerto Tejada','Puerto Tejada'),
('25','Puerto Triunfo','Puerto Triunfo'),
('25','Puerto Valencia','Puerto Valencia'),
('25','Puerto Wilches','Puerto Wilches'),
('25','Pupiales','Pupiales'),
('25','Purace','Purace'),
('25','Purificación','Purificación'),
('25','Purísima','Purísima'),
('25','Quebradanegra','Quebradanegra'),
('25','Queremal','Queremal'),
('25','Quetame','Quetame'),
('25','Quibdo','Quibdo'),
('25','Quimbaya','Quimbaya'),
('25','Quinchia','Quinchia'),
('25','Quipile','Quipile'),
('25','Quituro','Quituro'),
('25','Ragonvalia','Ragonvalia'),
('25','Ramiriqui','Ramiriqui'),
('25','Raquira','Raquira'),
('25','Recetor','Recetor'),
('25','Remedios','Remedios'),
('25','Remolino','Remolino'),
('25','Remolino del Caguan','Remolino del Caguan'),
('25','Repelon','Repelon'),
('25','Restrepo','Restrepo'),
('25','Ricaurte','Ricaurte'),
('25','Río Blanco','Río Blanco'),
('25','Río de Oro','Río de Oro'),
('25','Rioblanco','Rioblanco'),
('25','Riofrío','Riofrío'),
('25','Riogrande','Riogrande'),
('25','Riohacha','Riohacha'),
('25','Rionegro','Rionegro'),
('25','Riosucio','Riosucio'),
('25','Rioviejo','Rioviejo'),
('25','Risaralda','Risaralda'),
('25','Rivera','Rivera'),
('25','Roldanillo','Roldanillo'),
('25','Roncesvalles','Roncesvalles'),
('25','Rosas','Rosas'),
('25','Rotinet','Rotinet'),
('25','Rovira','Rovira'),
('25','Rozo','Rozo'),
('25','Rural Edatel (Medellín),','Rural Edatel (Medellín),'),
('25','Sabana de Torres','Sabana de Torres'),
('25','Sabana Grande','Sabana Grande'),
('25','Sabanalarga','Sabanalarga'),
('25','Saboya','Saboya'),
('25','Sachica','Sachica'),
('25','Sahagún','Sahagún'),
('25','Salado Blanco','Salado Blanco'),
('25','Salamina','Salamina'),
('25','Salazar','Salazar'),
('25','Saldaña','Saldaña'),
('25','Salento','Salento'),
('25','Salgar','Salgar'),
('25','Samaca','Samaca'),
('25','Samana','Samana'),
('25','Samanga','Samanga'),
('25','Samaniego','Samaniego'),
('25','Samaria','Samaria'),
('25','Sampues','Sampues'),
('25','San Agustín','San Agustín'),
('25','San Alberto','San Alberto'),
('25','San Andrés','San Andrés'),
('25','San Andrés (Isla),','San Andrés (Isla),'),
('25','San Andrés de Cuerquia','San Andrés de Cuerquia'),
('25','San Andrés de Sotavento','San Andrés de Sotavento'),
('25','San Andrés Pisimbala','San Andrés Pisimbala'),
('25','San Antero','San Antero'),
('25','San Antonio','San Antonio'),
('25','San Antonio Cabal','San Antonio Cabal'),
('25','San Antonio Chami','San Antonio Chami'),
('25','San Antonio de Tequendama','San Antonio de Tequendama'),
('25','San Antonio Getucha','San Antonio Getucha'),
('25','San Bartolomé','San Bartolomé'),
('25','San Benito','San Benito'),
('25','San Bernardo','San Bernardo'),
('25','San Bernardo del Viento','San Bernardo del Viento'),
('25','San Calixto','San Calixto'),
('25','San Carlos','San Carlos'),
('25','San Carlos de Guaroa','San Carlos de Guaroa'),
('25','San Cayetano','San Cayetano'),
('25','San Diego','San Diego'),
('25','San Estanislao','San Estanislao'),
('25','San Felipe','San Felipe'),
('25','San Félix','San Félix'),
('25','San Fernando','San Fernando'),
('25','San Francisco','San Francisco'),
('25','San Gil','San Gil'),
('25','San Jacinto','San Jacinto'),
('25','San Jacinto del Cauca','San Jacinto del Cauca'),
('25','San Jerónimo','San Jerónimo'),
('25','San Joaquín','San Joaquín'),
('25','San José','San José'),
('25','San José de','San José de'),
('25','San José de Fragua','San José de Fragua'),
('25','San José de Isnos','San José de Isnos'),
('25','San José de Miranda','San José de Miranda'),
('25','San José de Nus','San José de Nus'),
('25','San José de Pare','San José de Pare'),
('25','San Jose de Risaralda','San Jose de Risaralda'),
('25','San José de Risaralda','San José de Risaralda'),
('25','San José de Urama','San José de Urama'),
('25','San José del Guaviare','San José del Guaviare'),
('25','San José del Palmar','San José del Palmar'),
('25','San José Oriente','San José Oriente'),
('25','San Juan Carretera','San Juan Carretera'),
('25','San Juan de Arama','San Juan de Arama'),
('25','San Juan de Atacuari','San Juan de Atacuari'),
('25','San Juan de Betulia','San Juan de Betulia'),
('25','San Juan de Nepomuceno','San Juan de Nepomuceno'),
('25','San Juan de Rioseco','San Juan de Rioseco'),
('25','San Juan de Uraba','San Juan de Uraba'),
('25','San Juan del Cesar','San Juan del Cesar'),
('25','San Lorenzo','San Lorenzo'),
('25','San Luis','San Luis'),
('25','San Luis de Gaceno','San Luis de Gaceno'),
('25','San Luis de Palenque','San Luis de Palenque'),
('25','San Marcos','San Marcos'),
('25','San Martín','San Martín'),
('25','San Martín de Loba','San Martín de Loba'),
('25','San Mateo','San Mateo'),
('25','San Miguel','San Miguel'),
('25','San Miguel de Sema','San Miguel de Sema'),
('25','San Onofre','San Onofre'),
('25','San Pablo','San Pablo'),
('25','San Pablo de Borbur','San Pablo de Borbur'),
('25','San Pedro','San Pedro'),
('25','San Pedro de Los Milagros','San Pedro de Los Milagros'),
('25','San Pedro de Uraba','San Pedro de Uraba'),
('25','San Pelayo','San Pelayo'),
('25','San Rafael','San Rafael'),
('25','San Rafael de Rionegro','San Rafael de Rionegro'),
('25','San Roque','San Roque'),
('25','San Vicente','San Vicente'),
('25','San Vicente de Chucuri','San Vicente de Chucuri'),
('25','San Vicente del Caguan','San Vicente del Caguan'),
('25','Sandona','Sandona'),
('25','Santa Ana','Santa Ana'),
('25','Santa Bárbara','Santa Bárbara'),
('25','Santa Catalina','Santa Catalina'),
('25','Santa Cecilia','Santa Cecilia'),
('25','Santa Helena','Santa Helena'),
('25','Santa Inés','Santa Inés'),
('25','Santa Isabel','Santa Isabel'),
('25','Santa Lucía','Santa Lucía'),
('25','Santa María','Santa María'),
('25','Santa Marta','Santa Marta'),
('25','Santa Rita','Santa Rita'),
('25','Santa Rita de Andes','Santa Rita de Andes'),
('25','Santa Rosa','Santa Rosa'),
('25','Santa Rosa de Cabal','Santa Rosa de Cabal'),
('25','Santa Rosa de Osos','Santa Rosa de Osos'),
('25','Santa Rosa de Viterbo','Santa Rosa de Viterbo'),
('25','Santa Rosa del Sur','Santa Rosa del Sur'),
('25','Santa Rosa Norte','Santa Rosa Norte'),
('25','Santa Rosalía','Santa Rosalía'),
('25','Santa Sofía','Santa Sofía'),
('25','Santa Teresa','Santa Teresa'),
('25','Santafé Antioquía','Santafé Antioquía'),
('25','Santana','Santana'),
('25','Santander de Quilichao','Santander de Quilichao'),
('25','Santandercito','Santandercito'),
('25','Santiago','Santiago'),
('25','Santiago Pérez','Santiago Pérez'),
('25','Santo Domingo','Santo Domingo'),
('25','Santo Tomás','Santo Tomás'),
('25','Santuario','Santuario'),
('25','Sapzurro','Sapzurro'),
('25','Saravena','Saravena'),
('25','Sardinata','Sardinata'),
('25','Sasaima','Sasaima'),
('25','Sativanorte','Sativanorte'),
('25','Segovia','Segovia'),
('25','Sesquile','Sesquile'),
('25','Sevilla','Sevilla'),
('25','Siachoque','Siachoque'),
('25','Siberia','Siberia'),
('25','Sibundoy','Sibundoy'),
('25','Silos','Silos'),
('25','Silvania','Silvania'),
('25','Silvia','Silvia'),
('25','Simacota','Simacota'),
('25','Simijaca','Simijaca'),
('25','Simiti','Simiti'),
('25','Since','Since'),
('25','Sincelejo','Sincelejo'),
('25','Sincerin','Sincerin'),
('25','Sipi','Sipi'),
('25','Sitinuevo ','Sitinuevo '),
('25','Soata','Soata'),
('25','Socha','Socha'),
('25','Socorro','Socorro'),
('25','Socota','Socota'),
('25','Sogamoso','Sogamoso'),
('25','Solano','Solano'),
('25','Solita','Solita'),
('25','Somondoco','Somondoco'),
('25','Sonso','Sonso'),
('25','Sonson','Sonson'),
('25','Sopetran','Sopetran'),
('25','Soplaviento','Soplaviento'),
('25','Sopo','Sopo'),
('25','Sotaquira','Sotaquira'),
('25','Suaita','Suaita'),
('25','Suan','Suan'),
('25','Suárez','Suárez'),
('25','Suaza','Suaza'),
('25','Subachoque','Subachoque'),
('25','Subia','Subia'),
('25','Sucre','Sucre'),
('25','Suesca','Suesca'),
('25','Supata','Supata'),
('25','Supia','Supia'),
('25','Surata','Surata'),
('25','Susa','Susa'),
('25','Susacon','Susacon'),
('25','Sutamarchan','Sutamarchan'),
('25','Sutatausa','Sutatausa'),
('25','Sutatenza','Sutatenza'),
('25','Tabio','Tabio'),
('25','Tado','Tado'),
('25','Talaigua Nuevo','Talaigua Nuevo'),
('25','Tamalameque','Tamalameque'),
('25','Tamara','Tamara'),
('25','Tame','Tame'),
('25','Tamesis','Tamesis'),
('25','Támesis','Támesis'),
('25','Taparcal','Taparcal'),
('25','Taparto','Taparto'),
('25','Taraira','Taraira'),
('25','Tarapaca','Tarapaca'),
('25','Tarapacá','Tarapacá'),
('25','Taraza','Taraza'),
('25','Tarqui','Tarqui'),
('25','Tarso','Tarso'),
('25','Tasco','Tasco'),
('25','Tauramena','Tauramena'),
('25','Tausa','Tausa'),
('25','Telefonía','Telefonía'),
('25','Tello','Tello'),
('25','Tena','Tena'),
('25','Tenerife','Tenerife'),
('25','Tenjo','Tenjo'),
('25','Tenza','Tenza'),
('25','Teorama','Teorama'),
('25','Teresita','Teresita'),
('25','Teruel','Teruel'),
('25','Tesalia','Tesalia'),
('25','Tibacuy','Tibacuy'),
('25','Tibana','Tibana'),
('25','Tibasosa','Tibasosa'),
('25','Tibirita','Tibirita'),
('25','Tibu','Tibu'),
('25','Tienda Nueva','Tienda Nueva'),
('25','Tierralta','Tierralta'),
('25','Timana','Timana'),
('25','Timbio','Timbio'),
('25','Timbiqui','Timbiqui'),
('25','Tinjaca','Tinjaca'),
('25','Tipacoque','Tipacoque'),
('25','Titiribi','Titiribi'),
('25','Titribi','Titribi'),
('25','Tobia','Tobia'),
('25','Toca','Toca'),
('25','Tocaima','Tocaima'),
('25','Tocancipa','Tocancipa'),
('25','Togui','Togui'),
('25','Toledo','Toledo'),
('25','Tolu','Tolu'),
('25','Toluviejo','Toluviejo'),
('25','Tona','Tona'),
('25','Topaga','Topaga'),
('25','Topaipi','Topaipi'),
('25','Toribio','Toribio'),
('25','Toro','Toro'),
('25','Totoro','Totoro'),
('25','Tres Esquinas','Tres Esquinas'),
('25','Trinidad','Trinidad'),
('25','Troncoso','Troncoso'),
('25','Trujillo','Trujillo'),
('25','Tubara','Tubara'),
('25','Tulua','Tulua'),
('25','Tumaco','Tumaco'),
('25','Tunia','Tunia'),
('25','Tunja','Tunja'),
('25','Tuquerres','Tuquerres'),
('25','Turbana','Turbana'),
('25','Turbo','Turbo'),
('25','Turmeque','Turmeque'),
('25','Tuta','Tuta'),
('25','Ubala','Ubala'),
('25','Ubaque','Ubaque'),
('25','Ubate','Ubate'),
('25','Ulloa','Ulloa'),
('25','Une','Une'),
('25','Unguia','Unguia'),
('25','Uniabastos','Uniabastos'),
('25','Uramita','Uramita'),
('25','Uribia','Uribia'),
('25','Urra','Urra'),
('25','Urrao','Urrao'),
('25','Urumita','Urumita'),
('25','Usiacuri','Usiacuri'),
('25','Utica','Utica'),
('25','Vado Real','Vado Real'),
('25','Valdivia','Valdivia'),
('25','Valencia','Valencia'),
('25','Valle de San José','Valle de San José'),
('25','Valle de San Juan','Valle de San Juan'),
('25','Valledupar','Valledupar'),
('25','Valparaiso','Valparaiso'),
('25','Valparaíso','Valparaíso'),
('25','Vegachi','Vegachi'),
('25','Vegalarga','Vegalarga'),
('25','Vélez','Vélez'),
('25','Velu','Velu'),
('25','Venadillo','Venadillo'),
('25','Venecia','Venecia'),
('25','Ventaquemada','Ventaquemada'),
('25','Vergara','Vergara'),
('25','Versalles','Versalles'),
('25','Vetas','Vetas'),
('25','Viani','Viani'),
('25','Victoria','Victoria'),
('25','Vigia del Fuerte','Vigia del Fuerte'),
('25','Vijes','Vijes'),
('25','Villa de Leyva','Villa de Leyva'),
('25','Villa del Rosario','Villa del Rosario'),
('25','Villa Garzón','Villa Garzón'),
('25','Villacaro','Villacaro'),
('25','Villagómez','Villagómez'),
('25','Villagorgona','Villagorgona'),
('25','Villahermosa','Villahermosa'),
('25','Villanueva','Villanueva'),
('25','Villapinzón','Villapinzón'),
('25','Villarrica','Villarrica'),
('25','Villavicencio','Villavicencio'),
('25','Villavieja','Villavieja'),
('25','Villeta','Villeta'),
('25','Viota','Viota'),
('25','Viracacha','Viracacha'),
('25','Vistahermosa','Vistahermosa'),
('25','Viterbo','Viterbo'),
('25','Volcan N1','Volcan N1'),
('25','Yacopi','Yacopi'),
('25','Yaguara','Yaguara'),
('25','Yali','Yali'),
('25','Yarumal','Yarumal'),
('25','Yolombo','Yolombo'),
('25','Yondo','Yondo'),
('25','Yopal','Yopal'),
('25','Yotoco','Yotoco'),
('25','Yumbo','Yumbo'),
('25','Yurayaco','Yurayaco'),
('25','Zambrano','Zambrano'),
('25','Zapatoca','Zapatoca'),
('25','Zaragoza','Zaragoza'),
('25','Zarzal','Zarzal'),
('25','Zetaquira','Zetaquira'),
('25','Zipacon','Zipacon'),
('25','Zipaquira','Zipaquira'),
('25','Zuluaga','Zuluaga');