INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('23','Brampton','Brampton'),
('23','Burnaby','Burnaby'),
('23','Calgary','Calgary'),
('23','Charlottetown','Charlottetown'),
('23','Edmonton','Edmonton'),
('23','Gatineau','Gatineau'),
('23','Halifax','Halifax'),
('23','Hamilton','Hamilton'),
('23','Kitchener','Kitchener'),
('23','Laval','Laval'),
('23','London','London'),
('23','Longueuil','Longueuil'),
('23','Mississauga','Mississauga'),
('23','Moncton','Moncton'),
('23','Montreal','Montreal'),
('23','Ottawa','Ottawa'),
('23','Quebec','Quebec'),
('23','Regina','Regina'),
('23','Richmond','Richmond'),
('23','Saint John','Saint John'),
('23','Saint Johns','Saint Johns'),
('23','Saskatoon','Saskatoon'),
('23','St. Johns','St. Johns'),
('23','Surrey','Surrey'),
('23','Toronto','Toronto'),
('23','Vancouver','Vancouver'),
('23','Victoria','Victoria'),
('23','Whitehorse','Whitehorse'),
('23','Winnipeg','Winnipeg'),
('23','Yellowknife','Yellowknife');