INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('29','Alburquerque','Alburquerque'),
('29','Atlanta','Atlanta'),
('29','Baltimore','Baltimore'),
('29','Boston','Boston'),
('29','Charlotte','Charlotte'),
('29','Chicago','Chicago'),
('29','Columbus','Columbus'),
('29','Denver','Denver'),
('29','Detroit','Detroit'),
('29','Filadelfia','Filadelfia'),
('29','Honolulu','Honolulu'),
('29','Houston','Houston'),
('29','Indianapolis','Indianapolis'),
('29','Jacksonville','Jacksonville'),
('29','Las Vegas','Las Vegas'),
('29','Los çngeles','Los çngeles'),
('29','Menfis','Menfis'),
('29','Milwaukee','Milwaukee'),
('29','North Kansas City','North Kansas City'),
('29','Nueva Orleans','Nueva Orleans'),
('29','Nueva York','Nueva York'),
('29','Oklahoma City','Oklahoma City'),
('29','Omaha','Omaha'),
('29','Phoenix','Phoenix'),
('29','Portland','Portland'),
('29','San Antonio','San Antonio'),
('29','San Diego','San Diego'),
('29','Seattle','Seattle'),
('29','Virginia Beach','Virginia Beach'),
('29','Washington','Washington');