INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('32','Acapulco','Acapulco'),
('32','Aguascalientes','Aguascalientes'),
('32','Cancœn','Cancœn'),
('32','Chihuahua','Chihuahua'),
('32','Ciudad Juárez','Ciudad Juárez'),
('32','Ciudad Nezahualcóyotl','Ciudad Nezahualcóyotl'),
('32','Ciudad de México','Ciudad de México'),
('32','Cuernavaca','Cuernavaca'),
('32','Culiacán','Culiacán'),
('32','Ecatepec','Ecatepec'),
('32','Guadalajara','Guadalajara'),
('32','Hermosillo','Hermosillo'),
('32','León','León'),
('32','Monterrey','Monterrey'),
('32','Morelia','Morelia'),
('32','Mérida','Mérida'),
('32','Oaxaca de Juárez','Oaxaca de Juárez'),
('32','Pachuca','Pachuca'),
('32','Puebla de Zaragoza','Puebla de Zaragoza'),
('32','Querétaro','Querétaro'),
('32','Reynosa','Reynosa'),
('32','Saltillo','Saltillo'),
('32','San Luis Potosí','San Luis Potosí'),
('32','Tepic','Tepic'),
('32','Tijuana','Tijuana'),
('32','Tuxtla Gutiérrez','Tuxtla Gutiérrez'),
('32','Veracruz','Veracruz'),
('32','Victoria de Durango','Victoria de Durango'),
('32','Villahermosa','Villahermosa'),
('32','Zapopan','Zapopan');