INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('30','Antigua Guatemala','Antigua Guatemala'),
('30','Barberena','Barberena'),
('30','Chichicastenango','Chichicastenango'),
('30','Chimaltenango','Chimaltenango'),
('30','Chiquimula','Chiquimula'),
('30','Ciudad Guatemala','Ciudad Guatemala'),
('30','Coatepeque','Coatepeque'),
('30','Cobán','Cobán'),
('30','Escuintla','Escuintla'),
('30','Huehuetenango','Huehuetenango'),
('30','Jacaltenango','Jacaltenango'),
('30','Jalapa','Jalapa'),
('30','Jutiapa','Jutiapa'),
('30','Mazatenango','Mazatenango'),
('30','Mixco','Mixco'),
('30','Petapa','Petapa'),
('30','Puerto Barrios','Puerto Barrios'),
('30','Quetzaltenango','Quetzaltenango'),
('30','Retalhuleu','Retalhuleu'),
('30','San Benito','San Benito'),
('30','San Francisco El Alto','San Francisco El Alto'),
('30','San Juan Sacatepéquez','San Juan Sacatepéquez'),
('30','San Miguel Chicaj','San Miguel Chicaj'),
('30','San Pedro Sacatepéquez','San Pedro Sacatepéquez'),
('30','Sanarate','Sanarate'),
('30','Santa Lucía Cotzumalguapa','Santa Lucía Cotzumalguapa'),
('30','Sololá','Sololá'),
('30','Totonicapán','Totonicapán'),
('30','Villa Nueva','Villa Nueva'),
('30','Zacapa','Zacapa');