INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('28','Acajutla','Acajutla'),
('28','Ahuachapán','Ahuachapán'),
('28','Antiguo Cuscatlán','Antiguo Cuscatlán'),
('28','Apopa','Apopa'),
('28','Chalatenango','Chalatenango'),
('28','Chalchuapa','Chalchuapa'),
('28','Cojutepeque','Cojutepeque'),
('28','Cuscatancingo','Cuscatancingo'),
('28','Delgado','Delgado'),
('28','Izalco','Izalco'),
('28','La Unián','La Unián'),
('28','Mejicanos','Mejicanos'),
('28','Metapán','Metapán'),
('28','Puerto El Triunfo','Puerto El Triunfo'),
('28','Quezaltepeque','Quezaltepeque'),
('28','San Francisco','San Francisco'),
('28','San Marcos','San Marcos'),
('28','San Martín','San Martín'),
('28','San Miquel','San Miquel'),
('28','San Rafael Oriente','San Rafael Oriente'),
('28','San Salvador','San Salvador'),
('28','San Vicente','San Vicente'),
('28','Santa Ana','Santa Ana'),
('28','Santa Rosa de Lima','Santa Rosa de Lima'),
('28','Santa Tecla','Santa Tecla'),
('28','Sensuntepeque','Sensuntepeque'),
('28','Sonsonate','Sonsonate'),
('28','Soyapango','Soyapango'),
('28','Usulután','Usulután'),
('28','Zacatecoluca','Zacatecoluca');