INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('31','Choloma','Choloma'),
('31','Ciudad Choluteca','Ciudad Choluteca'),
('31','Comayagua','Comayagua'),
('31','Danlí','Danlí'),
('31','El Paraíso','El Paraíso'),
('31','El Progreso','El Progreso'),
('31','Gracias','Gracias'),
('31','Intibucá','Intibucá'),
('31','Juticalpa','Juticalpa'),
('31','La Ceiba','La Ceiba'),
('31','La Entrada','La Entrada'),
('31','La Lima','La Lima'),
('31','La Paz','La Paz'),
('31','Marcala','Marcala'),
('31','Nacaome','Nacaome'),
('31','Nueva Ocotepeque','Nueva Ocotepeque'),
('31','Olanchito','Olanchito'),
('31','Puerto Cortez','Puerto Cortez'),
('31','Puerto Lempira','Puerto Lempira'),
('31','Roatán','Roatán'),
('31','San Lorenzo','San Lorenzo'),
('31','San Pedro Sula','San Pedro Sula'),
('31','Santa Bárbara','Santa Bárbara'),
('31','Santa Rosa de Copán','Santa Rosa de Copán'),
('31','Siguatepeque','Siguatepeque'),
('31','Talanga','Talanga'),
('31','Tegucigalpa','Tegucigalpa'),
('31','Tela','Tela'),
('31','Tocoa','Tocoa'),
('31','Villanueva','Villanueva');