INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('33','Bluefields','Bluefields'),
('33','Boaco','Boaco'),
('33','Camoapa','Camoapa'),
('33','Chichigalpa','Chichigalpa'),
('33','Chinandega','Chinandega'),
('33','Ciudad Sandino','Ciudad Sandino'),
('33','Diriamba','Diriamba'),
('33','El Viejo','El Viejo'),
('33','Estelí','Estelí'),
('33','Granada','Granada'),
('33','Jalapa','Jalapa'),
('33','Jinotega','Jinotega'),
('33','Jinotepe','Jinotepe'),
('33','Juigalpa','Juigalpa'),
('33','León','León'),
('33','Managua','Managua'),
('33','Masatepe','Masatepe'),
('33','Masaya','Masaya'),
('33','Matagalpa','Matagalpa'),
('33','Nagarote','Nagarote'),
('33','Nandaime','Nandaime'),
('33','Nueva Guinea','Nueva Guinea'),
('33','Ocotal','Ocotal'),
('33','Puerto Cabezas','Puerto Cabezas'),
('33','Rivas','Rivas'),
('33','Río Blanco','Río Blanco'),
('33','San Carlos','San Carlos'),
('33','Siuna','Siuna'),
('33','Somoto','Somoto'),
('33','Tipitapa','Tipitapa');