INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('26','Alajuela','Alajuela'),
('26','Cartago','Cartago'),
('26','Caóas','Caóas'),
('26','Chacarita','Chacarita'),
('26','Curridabat','Curridabat'),
('26','Esparza','Esparza'),
('26','Guápiles','Guápiles'),
('26','Heredia','Heredia'),
('26','Liberia','Liberia'),
('26','Limón','Limón'),
('26','Mercedes','Mercedes'),
('26','Nicoya','Nicoya'),
('26','Paraíso','Paraíso'),
('26','Puntarenas','Puntarenas'),
('26','Purral','Purral'),
('26','Quesada','Quesada'),
('26','San Diego','San Diego'),
('26','San Francisco','San Francisco'),
('26','San Isidro','San Isidro'),
('26','San José','San José'),
('26','San Miguel','San Miguel'),
('26','San Pablo','San Pablo'),
('26','San Pedro','San Pedro'),
('26','San Rafael','San Rafael'),
('26','San Vicente','San Vicente'),
('26','San Vicente de Moravia','San Vicente de Moravia'),
('26','Santa Cruz','Santa Cruz'),
('26','Siquirres','Siquirres'),
('26','Turrialba','Turrialba');