INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('34','Aguadulce','Aguadulce'),
('34','Almirante','Almirante'),
('34','Antón','Antón'),
('34','Arraiján','Arraiján'),
('34','Bocas del Toro','Bocas del Toro'),
('34','Cativá','Cativá'),
('34','Changuinola','Changuinola'),
('34','Chilibre','Chilibre'),
('34','Chitré','Chitré'),
('34','Ciudad de Colón','Ciudad de Colón'),
('34','Ciudad de Panamá','Ciudad de Panamá'),
('34','David','David'),
('34','La Chorrera','La Chorrera'),
('34','La Concepción','La Concepción'),
('34','La Palma','La Palma'),
('34','Las Cumbres','Las Cumbres'),
('34','Las Tablas','Las Tablas'),
('34','Los Santos','Los Santos'),
('34','Pacora','Pacora'),
('34','Pedregal','Pedregal'),
('34','Penonomé','Penonomé'),
('34','Puerto Armuelles','Puerto Armuelles'),
('34','Puerto Escondido','Puerto Escondido'),
('34','Sabanitas','Sabanitas'),
('34','San Miguelito','San Miguelito'),
('34','Santiago','Santiago'),
('34','Soná','Soná'),
('34','Tocumen','Tocumen'),
('34','Ustupo','Ustupo'),
('34','Vista Alegre','Vista Alegre');