INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('38','Caracas','Caracas'),
('38','Maracaibo','Maracaibo'),
('38','Valencia','Valencia'),
('38','Barquisimeto','Barquisimeto'),
('38','Maracay','Maracay'),
('38','Ciudad Guayana','Ciudad Guayana'),
('38','San Cristóbal','San Cristóbal'),
('38','Maturín','Maturín'),
('38','Barcelona','Barcelona'),
('38','Ciudad Bolívar','Ciudad Bolívar'),
('38','Cumaná','Cumaná'),
('38','Barinas','Barinas'),
('38','Cabimas','Cabimas'),
('38','Punto Fijo','Punto Fijo'),
('38','Puerto La Cruz','Puerto La Cruz'),
('38','Guarenas','Guarenas'),
('38','Los Teques','Los Teques'),
('38','Mérida','Mérida'),
('38','Ciudad Ojeda','Ciudad Ojeda'),
('38','Guanare','Guanare'),
('38','Turmero','Turmero'),
('38','Coro','Coro'),
('38','Guatire','Guatire'),
('38','Puerto Cabello','Puerto Cabello'),
('38','El Tigre','El Tigre'),
('38','Acarigua','Acarigua'),
('38','Carora','Carora'),
('38','Guacara','Guacara'),
('38','Santa Teresa del Tuy','Santa Teresa del Tuy'),
('38','San Fernando de Apure','San Fernando de Apure'),
('38','Carúpano','Carúpano'),
('38','La Victoria','La Victoria'),
('38','Cabudare','Cabudare'),
('38','Guigue','Guigue'),
('38','Villa de Cura','Villa de Cura'),
('38','Calabozo','Calabozo'),
('38','Araure','Araure'),
('38','Santa Bárbara del Zulia','Santa Bárbara del Zulia'),
('38','Santa Rita','Santa Rita'),
('38','Ocumare del Tuy','Ocumare del Tuy');