INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('27','Ambato','Ambato'),
('27','Azogues','Azogues'),
('27','Babahoyo','Babahoyo'),
('27','Boca Suno','Boca Suno'),
('27','Cuenca','Cuenca'),
('27','Durán','Durán'),
('27','Guaranda','Guaranda'),
('27','Guayaquil','Guayaquil'),
('27','Ibarra','Ibarra'),
('27','La Libertad','La Libertad'),
('27','La Troncal','La Troncal'),
('27','Latacunga','Latacunga'),
('27','Loja','Loja'),
('27','Macas','Macas'),
('27','Machala','Machala'),
('27','Manta','Manta'),
('27','Nueva Loja','Nueva Loja'),
('27','Otavalo','Otavalo'),
('27','Pasaje','Pasaje'),
('27','Portoviejo','Portoviejo'),
('27','Propicia','Propicia'),
('27','Puyo','Puyo'),
('27','Quevedo','Quevedo'),
('27','Quito','Quito'),
('27','Riobamba','Riobamba'),
('27','Rosa Zárate','Rosa Zárate'),
('27','San Gabriel','San Gabriel'),
('27','Santo Domingo de los Colorados','Santo Domingo de los Colorados'),
('27','Tena','Tena'),
('27','Zamora','Zamora');