INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('36','Abancay','Abancay'),
('36','Arequipa','Arequipa'),
('36','Ayacucho','Ayacucho'),
('36','Cajamarca','Cajamarca'),
('36','Callao','Callao'),
('36','Cerro de Pasco','Cerro de Pasco'),
('36','Chiclayo','Chiclayo'),
('36','Chimbote','Chimbote'),
('36','Chincha Alta','Chincha Alta'),
('36','Chosica','Chosica'),
('36','Cusco','Cusco'),
('36','Huancavelica','Huancavelica'),
('36','Huancayo','Huancayo'),
('36','Huaraz','Huaraz'),
('36','Hu‡nuco','Hu‡nuco'),
('36','Ica','Ica'),
('36','Iquitos','Iquitos'),
('36','Juliaca','Juliaca'),
('36','La Peca','La Peca'),
('36','Lima','Lima'),
('36','Moquegua','Moquegua'),
('36','Moyobamba','Moyobamba'),
('36','Piura','Piura'),
('36','Pucallpa','Pucallpa'),
('36','Puerto Maldonado','Puerto Maldonado'),
('36','Puno','Puno'),
('36','Sullana','Sullana'),
('36','Tacna','Tacna'),
('36','Trujillo','Trujillo'),
('36','Tumbes','Tumbes');