INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('22 ','Aracaju','Aracaju'),
('22 ','Belo Horizonte','Belo Horizonte'),
('22 ','Belém','Belém'),
('22 ','Boa Vista','Boa Vista'),
('22 ','Brasilia','Brasilia'),
('22 ','Campo Grande','Campo Grande'),
('22 ','Cuiabá','Cuiabá'),
('22 ','Curitiba','Curitiba'),
('22 ','Florianópolis','Florianópolis'),
('22 ','Fortaleza','Fortaleza'),
('22 ','Goiânia','Goiânia'),
('22 ','Guarulhos','Guarulhos'),
('22 ','Jaboatão','Jaboatão'),
('22 ','João Pessoa','João Pessoa'),
('22 ','Macapá','Macapá'),
('22 ','Maceió','Maceió'),
('22 ','Manaos','Manaos'),
('22 ','Natal','Natal'),
('22 ','Nova Iguaçu','Nova Iguaçu'),
('22 ','Palmas','Palmas'),
('22 ','Porto Velho','Porto Velho'),
('22 ','Puerto Alegre','Puerto Alegre'),
('22 ','Recife','Recife'),
('22 ','Rio Branco','Rio Branco'),
('22 ','Río de Janeiro','Río de Janeiro'),
('22 ','Salvador','Salvador'),
('22 ','São Luís','São Luís'),
('22 ','São Paulo','São Paulo'),
('22 ','Teresina','Teresina'),
('22 ','Vila Velha','Vila Velha');