INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('37','Artigas','Artigas'),
('37','Bella Unión','Bella Unión'),
('37','Carmelo','Carmelo'),
('37','Chuy','Chuy'),
('37','Colonia del Sacramento','Colonia del Sacramento'),
('37','Delta del Tigre','Delta del Tigre'),
('37','Dolores','Dolores'),
('37','Durazno','Durazno'),
('37','Florida','Florida'),
('37','Fray Bentos','Fray Bentos'),
('37','La Paz','La Paz'),
('37','Las Piedras','Las Piedras'),
('37','Maldonado','Maldonado'),
('37','Melo','Melo'),
('37','Mercedes','Mercedes'),
('37','Minas','Minas'),
('37','Montevideo','Montevideo'),
('37','Pando','Pando'),
('37','Paso de los Toros','Paso de los Toros'),
('37','Paysandú','Paysandú'),
('37','Rivera','Rivera'),
('37','Rocha','Rocha'),
('37','Río Branco','Río Branco'),
('37','Salto','Salto'),
('37','San Carlos','San Carlos'),
('37','San José de Mayo','San José de Mayo'),
('37','Tacuarembó','Tacuarembó'),
('37','Treinta y Tres','Treinta y Tres'),
('37','Trinidad','Trinidad'),
('37','Young','Young');