INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('35','Asunción','Asunción'),
('35','Ayolas','Ayolas'),
('35','Benjamín Aceval','Benjamín Aceval'),
('35','Caacupé','Caacupé'),
('35','Caaguazú','Caaguazú'),
('35','Capiatá','Capiatá'),
('35','Capitán Bado','Capitán Bado'),
('35','Ciudad del Este','Ciudad del Este'),
('35','Colonia Mariano Roque Alonso','Colonia Mariano Roque Alonso'),
('35','Concepción','Concepción'),
('35','Coronel Oviedo','Coronel Oviedo'),
('35','Encarnación','Encarnación'),
('35','Fernando de la Mora','Fernando de la Mora'),
('35','Filadelfia','Filadelfia'),
('35','Horqueta','Horqueta'),
('35','Itauguá','Itauguá'),
('35','Lambaré','Lambaré'),
('35','Limpio','Limpio'),
('35','Nemby','Nemby'),
('35','Paraguarí','Paraguarí'),
('35','Piribebuy','Piribebuy'),
('35','Presidente Franco','Presidente Franco'),
('35','San Antonio','San Antonio'),
('35','San Isidro de Curuguaty','San Isidro de Curuguaty'),
('35','San Juan Nepomuceno','San Juan Nepomuceno'),
('35','San Lorenzo','San Lorenzo'),
('35','San Pedro de Ycuamandiyú','San Pedro de Ycuamandiyú'),
('35','Santa Rita','Santa Rita'),
('35','Villa Elisa','Villa Elisa'),
('35','Villarrica','Villarrica');