INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('20','Bariloche','Bariloche'),
('20','Buenos Aires','Buenos Aires'),
('20','Ciudad de Salta','Ciudad de Salta'),
('20','Comodoro Rivadavia','Comodoro Rivadavia'),
('20','Concordia','Concordia'),
('20','Corrientes','Corrientes'),
('20','Córdoba','Córdoba'),
('20','Formosa','Formosa'),
('20','La Plata','La Plata'),
('20','La Rioja','La Rioja'),
('20','Mar del Plata','Mar del Plata'),
('20','Mendoza','Mendoza'),
('20','Neuquén','Neuquén'),
('20','Paraná','Paraná'),
('20','Posadas','Posadas'),
('20','Quilmes','Quilmes'),
('20','Resistencia','Resistencia'),
('20','Rosario','Rosario'),
('20','Río Cuarto','Río Cuarto'),
('20','Río Gallegos','Río Gallegos'),
('20','San Fernando del Valle de Catamarca','San Fernando del Valle de Catamarca'),
('20','San Juan','San Juan'),
('20','San Luis','San Luis'),
('20','San Miguel de Tucumán','San Miguel de Tucumán'),
('20','San Salvador de Jujuy','San Salvador de Jujuy'),
('20','Santa Fe','Santa Fe'),
('20','Santa Rosa','Santa Rosa'),
('20','Santiago del Estero','Santiago del Estero'),
('20','Trelew','Trelew'),
('20','Ushuaia','Ushuaia');