INSERT INTO public."CITY"("COUNTRY_ID", "NAME_ES", "NAME_EN") VALUES 
('24','Angol','Angol'),
('24','Antofagasta','Antofagasta'),
('24','Arica','Arica'),
('24','Calama','Calama'),
('24','Chillán','Chillán'),
('24','Coihaique','Coihaique'),
('24','Concepción','Concepción'),
('24','Copiapó','Copiapó'),
('24','Coquimbo','Coquimbo'),
('24','Curicó','Curicó'),
('24','Iquique','Iquique'),
('24','La Serena','La Serena'),
('24','Linares','Linares'),
('24','Los Ángeles','Los Ángeles'),
('24','Osorno','Osorno'),
('24','Ovalle','Ovalle'),
('24','Puerto Montt','Puerto Montt'),
('24','Punta Arenas','Punta Arenas'),
('24','Quilpué','Quilpué'),
('24','Rancagua','Rancagua'),
('24','San Bernardo','San Bernardo'),
('24','Santiago de Chile','Santiago de Chile'),
('24','Talca','Talca'),
('24','Talcahuano','Talcahuano'),
('24','Temuco','Temuco'),
('24','Valdivia','Valdivia'),
('24','Vallenar','Vallenar'),
('24','Valparaíso','Valparaíso'),
('24','Viña del Mar','Viña del Mar'),
('24','Viña causiño','Viña causiño');