INSERT INTO public."FOOD_BRAND"("NAME_ES", "NAME_EN", "SPECIE") VALUES 
('Adore Perros','Adore Perros','1'),
('Agility Adultos','Agility Adultos','1'),
('Agility Puppy','Agility Puppy','1'),
('Chuky Adulto','Chuky Adulto','1'),
('Chuky Cachorro','Chuky Cachorro','1'),
('Chuky Pup Nug','Chuky Pup Nug','1'),
('Diamond Nat Lamb & Rice','Diamond Nat Lamb & Rice','1'),
('Dog Chow Adultos','Dog Chow Adultos','1'),
('Dog Chow Cachorros','Dog Chow Cachorros','1'),
('Dog Chow Adultos + 7','Dog Chow Adultos + 7','1'),
('Dog Chow Adultos Senior','Dog Chow Adultos Senior','1'),
('Dog Chow Ligth','Dog Chow Ligth','1'),
('Dogourmet Carne Ad','Dogourmet Carne Ad','1'),
('Equilibrio Adultos Raza Mediana','Equilibrio Adultos Raza Mediana','1'),
('Equilibrio Adultos Raza Pequeña','Equilibrio Adultos Raza Pequeña','1'),
('Equilibrio Cachorros Raza Mediana','Equilibrio Cachorros Raza Mediana','1'),
('Equilibrio Cachorros Raza Pequeña','Equilibrio Cachorros Raza Pequeña','1'),
('Excellent Puppy','Excellent Puppy','1'),
('Faro Adultos','Faro Adultos','1'),
('Faro Blando Adultos','Faro Blando Adultos','1'),
('Faro Blando Cachorros','Faro Blando Cachorros','1'),
('Faro Carrochos','Faro Carrochos','1'),
('Filpo','Filpo','1'),
('Hills Adultos','Hills Adultos','1'),
('Hills Puppy','Hills Puppy','1'),
('Hills Science Diet Canine Adult','Hills Science Diet Canine Adult','1'),
('Hills Science Diet Canine Puppy','Hills Science Diet Canine Puppy','1'),
('Hills Sens Stomach Skin','Hills Sens Stomach Skin','1'),
('Hills Canire R/D','Hills Canire R/D','1'),
('Hills Canire Ad Ligth','Hills Canire Ad Ligth','1'),
('Hills Canire Z/D Low Allergen','Hills Canire Z/D Low Allergen','1'),
('Hills Canire I/D','Hills Canire I/D','1'),
('Max Buffet Razas Pequeñas','Max Buffet Razas Pequeñas','1'),
('Max Light','Max Light','1'),
('Max Adultos','Max Adultos','1'),
('Max Adultos Mature','Max Adultos Mature','1'),
('Max Adultos Ligth','Max Adultos Ligth','1'),
('Max Adultos Buffet','Max Adultos Buffet','1'),
('Max Adultos Cachorros','Max Adultos Cachorros','1'),
('Natural Perros Obesos','Natural Perros Obesos','1'),
('Naturalis Adultos','Naturalis Adultos','1'),
('Naturalis Cachorros','Naturalis Cachorros','1'),
('Nutra-Nuggets Cordero y Arroz','Nutra-Nuggets Cordero y Arroz','1'),
('Nutra-Nuggets Puppy','Nutra-Nuggets Puppy','1'),
('Nutra-Nuggets Mantenimiento','Nutra-Nuggets Mantenimiento','1'),
('Nutra-Nuggets Lite Senior','Nutra-Nuggets Lite Senior','1'),
('Nutrecan Urban','Nutrecan Urban','1'),
('Nutrecan Senior','Nutrecan Senior','1'),
('Nutrecan Campo','Nutrecan Campo','1'),
('Nutrien Libre de Granos','Nutrien Libre de Granos','1'),
('Nutrien Natural','Nutrien Natural','1'),
('Nutrien Natural Senior ','Nutrien Natural Senior ','1'),
('Nutrien Original Adulto','Nutrien Original Adulto','1'),
('Nutriss Cachorro Leche','Nutriss Cachorro Leche','1'),
('Nutriss Carne Veg','Nutriss Carne Veg','1'),
('Nutriss Pollo Veg','Nutriss Pollo Veg','1'),
('Pedigree Vital Etapa 3','Pedigree Vital Etapa 3','1'),
('Pedigree Vital Junior Etapa 2','Pedigree Vital Junior Etapa 2','1'),
('Pedigree Vital Cachorro Etapa 1','Pedigree Vital Cachorro Etapa 1','1'),
('ProPlan Adulto','ProPlan Adulto','1'),
('ProPlan Adultos','ProPlan Adultos','1'),
('ProPlan Adultos + 7','ProPlan Adultos + 7','1'),
('ProPlan Delicate','ProPlan Delicate','1'),
('ProPlan Exigent','ProPlan Exigent','1'),
('ProPlan Puppy','ProPlan Puppy','1'),
('ProPlan Reduce','ProPlan Reduce','1'),
('ProPlan Senior','ProPlan Senior','1'),
('ProPlan Sensitive Skin','ProPlan Sensitive Skin','1'),
('Ringo Cachorros','Ringo Cachorros','1'),
('Ringo Premium','Ringo Premium','1'),
('Royal Canin Mini Adulto','Royal Canin Mini Adulto','1'),
('Royal Canin Medium Adulto','Royal Canin Medium Adulto','1'),
('Royal Canin Maxi Adulto','Royal Canin Maxi Adulto','1'),
('Royal Canin Exigent','Royal Canin Exigent','1'),
('Royal Canin Mini Junior','Royal Canin Mini Junior','1'),
('Royal Canin Medium Junior','Royal Canin Medium Junior','1'),
('Royal Canin Maxi Junior','Royal Canin Maxi Junior','1'),
('Sabor & Vida Perros','Sabor & Vida Perros','1'),
('Taste of The Wild ','Taste of The Wild ','1'),
('Taste of The Wild Puppy','Taste of The Wild Puppy','1'),
('Total Max Buffet Adulto','Total Max Buffet Adulto','1'),
('Total Max Cachorro','Total Max Cachorro','1'),
('Total Max Senior Nature','Total Max Senior Nature','1'),
('Adore para Gatos','Adore para Gatos','2'),
('Cat Chow Adulto Activos','Cat Chow Adulto Activos','2'),
('Cat Chow Adulto Deli Mix','Cat Chow Adulto Deli Mix','2'),
('Cat Chow Adulto Pescado','Cat Chow Adulto Pescado','2'),
('Cat Chow Adulto Carne','Cat Chow Adulto Carne','2'),
('Cat Chow Gatitos','Cat Chow Gatitos','2'),
('Cat Chow Gatos','Cat Chow Gatos','2'),
('Cat Chow Vida Sana','Cat Chow Vida Sana','2'),
('Diamond Adulto Cat ','Diamond Adulto Cat ','2'),
('Diamond Kitten Cat','Diamond Kitten Cat','2'),
('Equilibrio Gato Adulto','Equilibrio Gato Adulto','2'),
('Equilibrio Gato Filothes','Equilibrio Gato Filothes','2'),
('Hills Adultos Small','Hills Adultos Small','2'),
('Hills Feline Hairball','Hills Feline Hairball','2'),
('Hills Gato Adulto Optimal','Hills Gato Adulto Optimal','2'),
('Hills Science Diet Feline Hairball','Hills Science Diet Feline Hairball','2'),
('Hills Science Diet Feline Kitten','Hills Science Diet Feline Kitten','2'),
('Max Cat Buffet','Max Cat Buffet','2'),
('Max Cat Sabores de Mar','Max Cat Sabores de Mar','2'),
('Max Gatitos','Max Gatitos','2'),
('Max Nuggets Gato','Max Nuggets Gato','2'),
('Mirringo','Mirringo','2'),
('Monello Cat Adultos','Monello Cat Adultos','2'),
('Monello Cat Castrados','Monello Cat Castrados','2'),
('Monello Cat Filhotes','Monello Cat Filhotes','2'),
('Natural Gatos Diabéticos ','Natural Gatos Diabéticos ','2'),
('Nutrience Natural Kitten','Nutrience Natural Kitten','2'),
('Nutrience Libre de granos','Nutrience Libre de granos','2'),
('Nutrience Natural Adulto','Nutrience Natural Adulto','2'),
('Nutra-Nuggets Gatos','Nutra-Nuggets Gatos','2'),
('ProPlan Adultos Gato','ProPlan Adultos Gato','2'),
('ProPlan Cat Urinary','ProPlan Cat Urinary','2'),
('ProPlan Kitten','ProPlan Kitten','2'),
('ProPlan Sterilized','ProPlan Sterilized','2'),
('Royal Canin Castrado Male','Royal Canin Castrado Male','2'),
('Royal Canin Castrado Female','Royal Canin Castrado Female','2'),
('Royal Canin Exigent','Royal Canin Exigent','2'),
('Royal Canin Sensible','Royal Canin Sensible','2'),
('Royal Canin Adult fit','Royal Canin Adult fit','2'),
('Sabor & Vida Gatos','Sabor & Vida Gatos','2'),
('Topcat','Topcat','2'),
('Whiskas Gatitos','Whiskas Gatitos','2'),
('Whiskas Camarón y Corvina','Whiskas Camarón y Corvina','2'),
('Whiskas Pescado','Whiskas Pescado','2'),
('Whiskas Carne','Whiskas Carne','2'),
('Whiskas Pollo y Leche','Whiskas Pollo y Leche','2');
