INSERT INTO public."RACE"("NAME_ES", "NAME_EN", "SPECIE") VALUES
('Abisinio','Abisinio','2'),
('Angora (Turco)','Angora (Turco)','2'),
('Asiatico Humo - Atigrado','Asiatico Humo - Atigrado','2'),
('Azul Ruso','Azul Ruso','2'),
('Balines','Balines','2'),
('Bengal','Bengal','2'),
('Bobtail Japones','Bobtail Japones','2'),
('Bombay','Bombay','2'),
('Bosque De Noruega','Bosque De Noruega','2'),
('Brasileño De Pelo Corto','Brasileño De Pelo Corto','2'),
('Britanico','Britanico','2'),
('British Shorthair','British Shorthair','2'),
('California Spangled Cat','California Spangled Cat','2'),
('Cartujo (Charetreux)','Cartujo (Charetreux)','2'),
('Cornish Rex','Cornish Rex','2'),
('Curl Americano','Curl Americano','2'),
('Cymric','Cymric','2'),
('Domestico Comun O Mestizo','Domestico Comun O Mestizo','2'),
('El Burmes','El Burmes','2'),
('Esfinge','Esfinge','2'),
('Expotico','Expotico','2'),
('Fold Escoces ','Fold Escoces ','2'),
('Foldex','Foldex','2'),
('Habana','Habana','2'),
('Himalayo','Himalayo','2'),
('Javanes','Javanes','2'),
('Korat','Korat','2'),
('Maine Coon','Maine Coon','2'),
('Manx','Manx','2'),
('Mau Egipcio','Mau Egipcio','2'),
('Munchkin','Munchkin','2'),
('Nebelung','Nebelung','2'),
('Ocicat','Ocicat','2'),
('Oriental','Oriental','2'),
('Pelicorto Americano','Pelicorto Americano','2'),
('Pelicorto Europeo','Pelicorto Europeo','2'),
('Persa','Persa','2'),
('Pixie Bob','Pixie Bob','2'),
('Ragdoll','Ragdoll','2'),
('Rex','Rex','2'),
('Sagrado De Birmania','Sagrado De Birmania','2'),
('Sagrados De Birmania','Sagrados De Birmania','2'),
('Siames','Siames','2'),
('Singapur','Singapur','2'),
('Skogkatt','Skogkatt','2'),
('Snowshoe','Snowshoe','2'),
('Sokoke','Sokoke','2'),
('Somali','Somali','2'),
('Tonquines','Tonquines','2'),
('Turkish Van -Van Turco','Turkish Van -Van Turco','2'),
('Criolla','Criolla','2'),
('Bosque Siberia','Bosque Siberia','2'),
('Criollo','Criollo','2');